main

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -10,18 +10,26 @@ jobs:
       - name: Get team members
         id: get_members
         run: |
-          curl -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer 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" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/orgs/uncoma-curza-lab/teams/peylw24/members > response.json
-          cat response.json
-          if jq -e .message response.json > /dev/null; then
-            echo "Error: $(jq -r .message response.json)"
-            exit 1
-          fi
-          jq -r '.[].login' response.json > members.txt
-          cat members.txt
+            page=1
+            while true; do
+                response=$(curl -L \
+                    -H "Accept: application/vnd.github+json" \
+                    -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" \
+                    -H "X-GitHub-Api-Version: 2022-11-28" \
+                    https://api.github.com/orgs/uncoma-curza-lab/teams/peylw24/members?page=$page)
+      
+                if ! jq -e '.[].login' <<< "$response" > members.txt; then
+                    echo "Error: $(jq -r .message <<< "$response")"
+                    exit 1
+                fi
+
+                # Check for next page link
+                next_page=$(jq -r '.["links"][] | select(.rel == "next")["href"]' <<< "$response")
+                if [[ -z "$next_page" ]]; then
+                    break
+                fi
+                page=$((page+1))
+            done
       - name: Generate member pages
         run: |
           while IFS= read -r member; do
@@ -35,14 +43,17 @@ jobs:
               echo "<li><a href=\"alumnos/$alumno/index.html\">$alumno</a></li>" >> index.html
             fi
           done < members.txt
-      - name: Update index.html
+
+      - name: Generate member pages (main index.html)
         run: |
-          # Clear the existing list of links
-          sed -i '/<li><a href="\/alumnos\/.*\/index\.html">.*<\/a><\/li>/d' index.html
-          # Append new links
-          while IFS= read -r member; do
-            echo "<li><a href=\"alumnos/$member/index.html\">$member</a></li>" >> index.html
-          done < members.txt
+            # Clear existing links from main index.html
+            sed -i '/<li><a href="\/alumnos\/.*\/index\.html">.*<\/a><\/li>/d' index.html
+
+            # Loop through members and add links to main index.html
+            while IFS= read -r member; do
+                echo "<li><a href=\"alumnos/$member/index.html\">$member</a></li>" >> index.html
+            done < members.txt
+
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
