Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,7 +1,7 @@
 name: Generate Member Pages
 on:
   push:
-    branches: [main]
+    branches: [crea_alumnos]
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -10,18 +10,19 @@ jobs:
       - name: Get team members
         id: get_members
         run: |
-          curl -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer 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" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/orgs/uncoma-curza-lab/teams/peylw24/members > response.json
-          cat response.json
-          if jq -e .message response.json > /dev/null; then
-            echo "Error: $(jq -r .message response.json)"
-            exit 1
-          fi
-          jq -r '.[].login' response.json > members.txt
-          cat members.txt
+            echo ${{ secrets.ACTIONS }}
+            curl -L \
+               -H "Accept: application/vnd.github+json" \
+                -H "Authorization: Bearer ${{ secrets.ACTIONS }}" \
+                -H "X-GitHub-Api-Version: 2022-11-28" \
+                https://api.github.com/orgs/uncoma-curza-lab/teams/peylw24/members?per_page=100 > response.json
+            if jq -e .message response.json > /dev/null; then
+                echo "Error: $(jq -r .message response.json)"
+                exit 1
+            fi
+            jq -r '.[].login' response.json > members.txt
+            echo "Number of members: $(wc -l members.txt)"
+
       - name: Generate member pages
         run: |
           while IFS= read -r member; do
@@ -30,25 +31,22 @@ jobs:
             # Check if the subdirectory already exists
             if [ ! -d "alumnos/$alumno" ]; then
               mkdir -p "alumnos/$alumno"
-              cp index.html "alumnos/$alumno/index.html"
-              sed -i "s/niunmango/$alumno/g" "alumnos/$alumno/index.html"
-              echo "<li><a href=\"alumnos/$alumno/index.html\">$alumno</a></li>" >> index.html
+              cp alumnos/niunmango/index.html "alumnos/$alumno/index.html"
             fi
           done < members.txt
-      - name: Update index.html
+
+      - name: Generate member pages (main index.html)
         run: |
-          # Clear the existing list of links
-          sed -i '/<li><a href="\/alumnos\/.*\/index\.html">.*<\/a><\/li>/d' index.html
-          # Append new links
-          while IFS= read -r member; do
-            echo "<li><a href=\"alumnos/$member/index.html\">$member</a></li>" >> index.html
-          done < members.txt
+            # Clear existing links from main index.html
+            sed -i '/<li><a href="\/alumnos\/.*\/index\.html">.*<\/a><\/li>/d' index.html
+
+            # Loop through members and add links to main index.html
+            while IFS= read -r member; do
+                echo "<li><a href=\"alumnos/$member/index.html\">$member</a></li>" >> index.html
+            done < members.txt
+
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: .
-
-
-          
-        
