Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,6 +18,11 @@ jobs:
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/orgs/uncoma-curza-lab/teams/peylw24/members > response.json
+          cat response.json
+          if jq -e .message response.json > /dev/null; then
+            echo "Error: $(jq -r .message response.json)"
+            exit 1
+          fi
           jq -r '.[].login' response.json > members.txt
           cat members.txt
 
